### ISSUE TITLE
No "about:" pages should be prevented from opening

### ISSUE THREAD

**Issue by axelsimon** [gebirgsbaerbel/max-tabs-limit#2]
I discovered max-tabs-limits can prevent `about:certificate?cert=XXXXX.` from opening.

Any and all `about:` pages should never be prevented from opening, as they are core to Firefox functionality :)

**Comment by gebirgsbaerbel** [comment]
Hey, thank you for letting me know. I thought I had all about pages. Will add it, probably this week :)

**Comment by gebirgsbaerbel** [comment]
Fixed the bug, now only about:newtab, about:home and about:welcome are blocked as they all open a newtab

**Comment by nc7s** [comment]
"Customize Toolbar" opens a new page, also blocked while shouldn't be. It's a special page with the URL `about:blank`, titled `Customize ${firefox_name}` (I use the developer edition which showed up as `Customize Firefox Developer Edition`).
